### Imports

In [8]:
import numpy as np
import pandas as pd
# import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, LabelEncoder

### Loading CSV // Normalize

In [12]:
# loads the data 
df = pd.read_csv("Dataset/ai4i2020.csv")
df = df.drop(columns=["UDI", "Product ID"])

# separates features and targets 
X = df.drop(columns=["Machine failure", "TWF", "HDF", "PWF", "OSF", "RNF"]) # targets 
y = df["Machine failure"]

# encodes categorical features
encoder = LabelEncoder()
X["Type"] = encoder.fit_transform(X["Type"])

# scales the numeric features 
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print(X_scaled)

[[ 1.33388944 -0.95238944 -0.94735989  0.06818514  0.28219976 -1.69598374]
 [-0.33222278 -0.90239341 -0.879959   -0.72947151  0.63330802 -1.6488517 ]
 [-0.33222278 -0.95238944 -1.01476077 -0.22744984  0.94428963 -1.61743034]
 ...
 [ 1.33388944 -0.50242514 -0.94735989  0.59251888 -0.66077672 -1.35034876]
 [-1.998335   -0.50242514 -0.879959   -0.72947151  0.85400464 -1.30321671]
 [ 1.33388944 -0.50242514 -0.879959   -0.2162938   0.02137647 -1.22466331]]
